import { Auth, withSSRContext } from "aws-amplify";
import { serializeModel } from '@aws-amplify/datastore/ssr';
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { Blog } from '../src/models';

export async function getServerSideProps({ req }) {
  const SSR = withSSRContext({ req });
  const blogData = await SSR.DataStore.query(Blog) 
  return {
    props: {
      blogs: serializeModel(blogData)
    }
  }
}

export default function Home({ blogs }) {
  const [user, setUser] = useState(null);
  useEffect(() => {
    const getUser = async () => {
      const user = await Auth.currentAuthenticatedUser();
      setUser(user);
    };
    getUser();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? <button onClick={async () => {
        Auth.signOut();
        setUser(null);
      }}>Sign out</button> : <Link href="/sign-in">Sign in</Link>}
      {
        blogs.map((blog) => {
          return (
            <>
              <h1>{blog.name}</h1>
            </>
          )
        })
      }
    </div>
  );
}
